# Generated by Django 4.1.7 on 2023-03-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=255)),
                ('art_type', models.CharField(choices=[('P', 'Painting'), ('C', 'Chariot'), ('O', 'Others'), ('H', 'Holding')], max_length=1)),
                ('category', models.CharField(choices=[('B', 'Borrowed'), ('P', 'Permenant')], max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedCollection',
            fields=[
                ('date_borrowed', models.DateTimeField()),
                ('date_returned', models.DateTimeField()),
                ('borrowed_art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='borrowed', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Chariot',
            fields=[
                ('object_number', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('chassis_number', models.IntegerField()),
                ('chariot_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='chariot_art', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('item_description', models.TextField()),
                ('art_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='item_description', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('material', models.CharField(max_length=255)),
                ('holding_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='holding_art', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('origin', models.CharField(max_length=255)),
                ('others_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='others_art', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('atrist_name', models.CharField(max_length=255)),
                ('painting_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='painting_art', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentCollection',
            fields=[
                ('date_aquired', models.DateTimeField()),
                ('permenant_art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='permenant', serialize=False, to='Arts.artobject')),
            ],
        ),
        migrations.CreateModel(
            name='ArtStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='Arts.artobject')),
            ],
        ),
        migrations.AddField(
            model_name='artobject',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='art_hall', to='Arts.hall'),
        ),
    ]
