# Generated by Django 4.1.7 on 2023-03-02 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='art_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='description', serialize=False, to='Arts.artobject'),
        ),
    ]
