# Generated by Django 4.1.7 on 2023-03-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arts', '0002_alter_artobject_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artobject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
