# Generated by Django 4.1.7 on 2023-03-03 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arts', '0003_alter_artobject_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artobject',
            options={'ordering': ['art_name']},
        ),
        migrations.RemoveField(
            model_name='artstory',
            name='id',
        ),
        migrations.AlterField(
            model_name='artstory',
            name='art',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=1, related_name='story', serialize=False, to='Arts.artobject'),
        ),
    ]
